algorithm:
  gamma: 0.9
render:
  fps: 2
  win_size: [800,600]

map_1x3: ["-SG"]
map_2x2: ["SX", "-G"]
map_3x3: ["SXS", "---", "X-G"]
map_4x4: ["S---", "-X-X", "---X", "X--G"]
map_5x5: 
  - "----X"
  - "SXX--"
  - "XGX--"
  - "----X"
map_8x8:
  - "S-------"
  - "--------"
  - "---X----"
  - "-----X--"
  - "---X----"
  - "--X---X-"
  - "-X--X-XX"
  - "---X---G"